c=open('backend/templates/index.html',encoding='utf-8').read()
o=c.count('{'); cl=c.count('}'); bt=c.count('`')
print(f'braces: {o}/{cl} bal={o-cl}')
print(f'backticks: {bt} even={bt%2==0}')
print(f'lines: {c.count(chr(10))}')
print('aside ok' if 'id="main-sidebar"' in c else 'ASIDE MISSING')
print('nav ok' if 'id="sidebar-nav"' in c else 'NAV MISSING')
print('ring ok' if 'logo-ring' in c else 'RING MISSING')
print('orb ok' if 'sidebar-orb' in c else 'ORB MISSING')
